theme: jekyll-theme-cayman
title: Python Multi-Modules ğŸ“¦
description: Implementing a Python workflow with multiple apps, packages and modules. The applications support containerized execution with Docker ğŸ³.
