name: Release-Applications

on:
  workflow_run:
    workflows: [ "Docker-Build" ]
    types:
      - completed


jobs:

  create-release:
    name: Release apps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ahmadnassri/action-workflow-run-wait@v1
    - name: Prepare App ğŸš€
      run: sudo apt-get install zip gzip tar
    - name: Create app archive ğŸ“¦
      run: |
        zip -r app1.zip src/app1
        zip -r app2.zip src/app2
        zip -r app3.zip src/app3
    - name: Create release with artifact
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "App â­ï¸"
        files: |
          app1.zip
          app2.zip
          app3.zip